-- MySQL Script generated by MySQL Workbench
-- ter 06 set 2022 17:24:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas_sucos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vendas_sucos` ;

-- -----------------------------------------------------
-- Table `vendas_sucos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`clientes` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(150) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `idade` INT NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NULL DEFAULT NULL,
  `limite_credito` FLOAT NULL DEFAULT NULL,
  `volume_compra` FLOAT NULL DEFAULT NULL,
  `primeira_compra` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`vendedores` (
  `matricula` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `comissao` FLOAT NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  `ferias` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`vendas` (
  `numero` VARCHAR(5) NOT NULL,
  `data_venda` DATE NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `matricula` VARCHAR(5) NOT NULL,
  `imposto` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`numero`),
  INDEX `cpf` (`cpf` ASC) VISIBLE,
  INDEX `matricula` (`matricula` ASC) VISIBLE,
  CONSTRAINT `vendas_ibfk_1`
    FOREIGN KEY (`cpf`)
    REFERENCES `vendas_sucos`.`clientes` (`cpf`)
    ON DELETE CASCADE,
  CONSTRAINT `vendas_ibfk_2`
    FOREIGN KEY (`matricula`)
    REFERENCES `vendas_sucos`.`vendedores` (`matricula`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`produtos` (
  `codigo` VARCHAR(10) NOT NULL,
  `descritor` VARCHAR(100) NULL DEFAULT NULL,
  `sabor` VARCHAR(50) NULL DEFAULT NULL,
  `tamanho` VARCHAR(50) NULL DEFAULT NULL,
  `embalagem` VARCHAR(50) NULL DEFAULT NULL,
  `preco_lista` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`itens_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`itens_notas` (
  `numero` VARCHAR(5) NOT NULL,
  `codigo_produto` VARCHAR(10) NOT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`numero`, `codigo_produto`),
  INDEX `codigo_produto` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `itens_notas_ibfk_1`
    FOREIGN KEY (`numero`)
    REFERENCES `vendas_sucos`.`vendas` (`numero`)
    ON DELETE CASCADE,
  CONSTRAINT `itens_notas_ibfk_2`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `vendas_sucos`.`produtos` (`codigo`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
